
# tasks file for hadoop-slave_role
  - name: copy java software
    copy:
      src: /root/jdk-8u171-linux-x64.rpm
      dest: /root/

  - name: Copy hadoop software
    copy:
      src: /root/hadoop-1.2.1-1.x86_64.rpm
      dest: /root/

  - name: "checking Jdk in the datanode"
    shell: "rpm -q jdk1.8-1.8.0_171-fcs.x86_64"
    register: jdk
    ignore_errors: yes

  - name: "Installing Jdk in the datanode"
    shell:  "rpm -ivh jdk-8u171-linux-x64.rpm"
    when: jdk.rc !=0
      
  - name: Installing hadoop software"
    command: "rpm -ivh hadoop-1.2.1-1.x86_64.rpm --force"
    ignore_errors: yes

  - name: "deleting directory"
    file:
      state: absent
      path: "{{ directory_name}}"
    ignore_errors: yes
    register: x

  - name: "Creating a directory"
    file:
      state: directory
      path: "{{ directory_name }}"
    when: x.state=='absent'

  - template:
      src: "templates/hdfs-site.xml"
      dest: "/etc/hadoop/hdfs-site.xml"

  - template:
      src: "templates/core-site.xml"
      dest: /etc/hadoop

  - name: "Stoping the datanode"
    shell: "hadoop-daemon.sh stop datanode"
    ignore_errors: yes
    register: hadoop_stopped

  - name: "Stopping hadoop"
    debug:
     var: hadoop_stopped.stdout
    ignore_errors: yes


  - shell: "hadoop-daemon.sh start datanode"
  
  - name: "java process"
    command: "jps"
    register: jps
  
  - name: "jps"
    debug:
      var: jps.stdout
  - name: "Running hadoop report"
    shell: "hadoop dfsadmin -report | less"
    register: report

  - name: "report of hadoop cluster"
    debug:
      var: report
